// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-sRBy6V6eBvEiR_Gh2Mme17I5VeAsA4',
    appId: '1:996613181308:web:1a71e96e6337687e779ef9',
    messagingSenderId: '996613181308',
    projectId: 'afrogame-50422',
    authDomain: 'afrogame-50422.firebaseapp.com',
    storageBucket: 'afrogame-50422.firebasestorage.app',
    measurementId: 'G-ZHQKKZQVQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxl50Tz7KyLGyCICz1gAmLkYoaQEurl8',
    appId: '1:996613181308:android:df97cbcc5703bcbf779ef9',
    messagingSenderId: '996613181308',
    projectId: 'afrogame-50422',
    storageBucket: 'afrogame-50422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9oK3J59kLU3gGlYT5dFgAvl4fT9WVTnM',
    appId: '1:996613181308:ios:d7f1a2cf93290a4d779ef9',
    messagingSenderId: '996613181308',
    projectId: 'afrogame-50422',
    storageBucket: 'afrogame-50422.firebasestorage.app',
    iosBundleId: 'com.afro.event.afroevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9oK3J59kLU3gGlYT5dFgAvl4fT9WVTnM',
    appId: '1:996613181308:ios:d7f1a2cf93290a4d779ef9',
    messagingSenderId: '996613181308',
    projectId: 'afrogame-50422',
    storageBucket: 'afrogame-50422.firebasestorage.app',
    iosBundleId: 'com.afro.event.afroevent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-sRBy6V6eBvEiR_Gh2Mme17I5VeAsA4',
    appId: '1:996613181308:web:6cf8327ef3e5f52f779ef9',
    messagingSenderId: '996613181308',
    projectId: 'afrogame-50422',
    authDomain: 'afrogame-50422.firebaseapp.com',
    storageBucket: 'afrogame-50422.firebasestorage.app',
    measurementId: 'G-69B0B9XGCW',
  );
}
